background #181216
foreground #ecdfe5
cursor #ecdfe5
cursor_text_color #181216
selection_background #9b8d95
selection_foreground #ecdfe5
color0 #181216
color1 #ffb4ab
color2 #f4b2e2
color3 #f5b9a4
color4 #dbbed1
color5 #f4b2e2
color6 #f5b9a4
color7 #ecdfe5
color8 #9b8d95
color9 #ffb4ab
color10 #f4b2e2
color11 #f5b9a4
color12 #dbbed1
color13 #f4b2e2
color14 #9b8d95
color15 #ffd7f1
